home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'
urlpatterns = [

    path("signup/", views.SignUpView.as_view(), name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("services/", views.services, name="services"),
    path('profile/', views.profile, name='profile'),
    path('add_pet_service/', views.add_pet_service, name='add_pet_service'),
    path("reservetime/", views.reservetime, name="reservetime"),
    path('reservation_success/', views.reservation_success, name='reservation_success'),
    path('', views.home, name="home"),

]

trustytails/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('django.contrib.auth.urls')),
    path("", include("home.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User


class AboutContent(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    objects = models.Manager()

    def __str__(self):
        return self.title


class PetService(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    photo = models.ImageField(upload_to='service_photos/', blank=True, null=True)
    objects = models.Manager()

    def __str__(self):
        return self.title


class ReserveTime(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pet_type = models.CharField(max_length=50)
    pets_numbers = models.FloatField()
    address = models.CharField(max_length=150, default='')
    date = models.DateField()
    time = models.TimeField()
    desired_service = models.ManyToManyField(PetService, blank=True)
    objects = models.Manager()

    TIME_CHOICES = (
        ('08:00', '08:00 AM'),
        ('08:30', '08:30 AM'),
        ('09:00', '09:00 AM'),
        ('09:30', '09:30 AM'),
        ('10:00', '10:00 AM'),
        ('10:30', '10:30 AM'),
        ('11:00', '11:00 AM'),
        ('11:30', '11:30 AM'),
        ('12:00', '12:00 PM'),
        ('12:30', '12:30 PM'),
        ('13:00', '13:00 PM'),
        ('13:30', '13:30 PM'),
        ('14:00', '14:00 PM'),
        ('14:30', '14:30 PM'),
        ('15:00', '15:00 PM'),
        ('15:30', '15:30 PM'),
        ('16:00', '16:00 PM'),
        ('16:30', '16:30 PM'),
        ('17:00', '17:00 PM'),
        ('17:30', '17:30 PM'),
        ('18:00', '18:00 PM'),
        ('18:30', '18:30 PM'),
        ('19:00', '19:00 PM'),
        ('19:30', '19:30 PM')
    )

    time_choice = models.CharField(max_length=5, choices=TIME_CHOICES, default='08:00')

    def __str__(self):
        return f"Reservation for {self.user} on {self.date} at {self.time}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=150, default='')
    desired_service = models.ManyToManyField(PetService, blank=True)
    objects = models.Manager()

    def __str__(self):
        return f'{self.user.username} Profile'

    def get_reservations(self):
        return Reservation.objects.filter(user=self.user)


class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reserved_time = models.DateTimeField()
    services = models.ManyToManyField(PetService)
    objects = models.Manager()

    def get_services_names(self):
        return ", ".join(str(service) for service in self.services.all())

    def __str__(self):
        return f"Reservation for {self.user} on {self.reserved_time} with services: {self.get_services_names()}"

home/forms.py
from django.contrib.auth import get_user_model
from .models import Profile, PetService, ReserveTime
from django.contrib.auth.forms import UserCreationForm
from django import forms


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=150)

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=commit)
        Profile.objects.get_or_create(user=user)
        return user


class ProfileUpdateForm(forms.ModelForm):
    email = forms.EmailField(max_length=150)

    class Meta:
        model = Profile
        fields = ()


class PetServiceForm(forms.ModelForm):
    class Meta:
        model = PetService
        fields = ['title', 'description']


class ReservationForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.ChoiceField(choices=ReserveTime.TIME_CHOICES)
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=150)
    services = forms.ModelMultipleChoiceField(
        queryset=PetService.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    PET_TYPE_CHOICES = (
        ('dog', 'Dog'),
        ('cat', 'Cat'),
        ('reptile', 'Reptile'),
        ('fish', 'Fish'),
    )
    pets_type = forms.ChoiceField(choices=PET_TYPE_CHOICES)

    class Meta:
        model = ReserveTime
        fields = ['name', 'email', 'pets_type', 'pets_numbers', 'address', 'date', 'time', 'services']

home/views.py
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import UpdateView
from .forms import CustomUserCreationForm, ProfileUpdateForm, PetServiceForm, ReservationForm
from .models import Profile, AboutContent, PetService, Reservation


def home(request):
    about_content = AboutContent.objects.first()
    return render(request, 'home.html', {'about_content': about_content})


class SignUpView(generic.CreateView):
    model = get_user_model()
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "signup.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        if not hasattr(self.object, 'profile'):
            Profile.objects.create(user=self.object)
            messages.success(self.request, 'Profile created successfully')
            return response
        else:
            messages.warning(self.request, 'Profile already exists')
            return redirect(reverse_lazy('login'))


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('home:profile')
    else:
        if not hasattr(request.user, 'profile'):
            Profile.objects.create(user=request.user)
        form = ProfileUpdateForm(instance=request.user.profile)
    reservations = request.user.profile.get_reservations()

    return render(request, 'profile.html', {'form': form, 'user_profile': request.user.profile,
                                            'reservations': reservations})


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileUpdateForm
    template_name = 'profile_update.html'
    success_url = '/profile/'


def services(request):
    services = PetService.objects.all()
    return render(request, 'services.html', {'services': services})


def add_pet_service(request):
    if request.method == 'POST':
        form = PetServiceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pet_service_list')
    else:
        form = PetServiceForm()
    return render(request, 'add_pet_service.html', {'form': form})


@login_required
def reservetime(request):
    user_profile, _ = Profile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            date = form.cleaned_data['date']
            time_choice = form.cleaned_data['time']
            services_ids = form.cleaned_data['services']

            time = datetime.strptime(time_choice, '%H:%M').time()
            reserved_time = datetime.combine(date, time)

            services = PetService.objects.filter(pk__in=services_ids)

            subject = 'Reservation Confirmation'
            message = f'Hello {name},\n\nYour reservation has been confirmed.' \
                      f'\n\nReservation Details:\nDate: {date}\nTime: {time_choice}' \
                      f'\nServices: {", ".join(str(service) for service in services)}' \
                      f'\n\nThank you for using our service!' \
                      f'\n\nBest regards,\nThe Reservation Team'
            send_mail(subject, message, 'your_default_from_email', [email])

            reservation = Reservation.objects.create(user=request.user, reserved_time=reserved_time)
            reservation.services.set(services)

            user_profile.desired_service.set(services)

            return redirect(reverse_lazy('home:reservation_success'))
    else:
        form = ReservationForm()

    return render(request, 'reservetime.html', {'form': form})


def reservation_success(request):
    reservation = Reservation.objects.filter(user=request.user).order_by('-id').first()
    return render(request, 'reservation_success.html', {'reservation': reservation})


def about_us(request):
    about_contents = AboutContent.objects.all()
    return render(request, 'about.html', {'about_contents': about_contents})

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <link rel="stylesheet" type="text/css" href="{% static 'static/home.css' %}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Trusty Tails{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="shortcut icon" type="image/png" href="/media/logo/logo.png" />
  <style>
    .navbar-brand img {
      height: 30px;
      margin-right: 10px;
    }
  </style>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:home' %}">
        <img src="/media/logo/logo.png" alt="Logo">
        Trusty Tails
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
     <div class="collapse navbar-collapse" id="navbarNav">
         <ul class="navbar-nav">
             <li class="nav-item">
                 <a class="nav-link" href="{% url 'home:services' %}">Our services</a>
             </li>
             <li class="nav-item">
                 <a class="nav-link" href="{% url 'home:reservetime' %}">Reserve time</a>
             </li>
             {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'home:profile' %}">Welcome, {{ user.username }}!</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:logout' %}">Log out</a>
            </li>
             {% else %}
             <li class="nav-item">
              <a class="nav-link" href="{% url 'home:signup' %}">Sign in</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="{% url 'home:login' %}">Login</a>
            </li>
             {% endif %}
        </ul>
     </div>
    </div>
  </nav>

  <div class="container mt-5">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="message {{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'static/home.css' %}">

  {% if about_content %}
    <div class="box">
      <h2>{{ about_content.title }}</h2>
      <p>{{ about_content.description }}</p>
    </div>
  {% endif %}

  <div class="boxes-container">
    <div class="box small-box">
      <a href="{% url 'home:reservetime' %}">Reserve time</a>
    </div>

    <div class="box small-box">
      <a href="{% url 'home:services' %}">Our services</a>
    </div>
  </div>

<style>
.box {
  border: 1px solid #ddd;
  padding: 10px;
  margin-bottom: 20px;
  border-radius: 4px;
  background-color: #f2f2f2;
}

.boxes-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
}

.small-box {
  width: 48%;
}
</style>

{% endblock %}